Bootstrap:docker
From:ubuntu:16.04

%post

    echo "The sun is shining, the weather is sweeeet..."
    echo "Make you wanna move..."

%runscript

    exec echo "You say please, but all I see is pizza.."
